# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/modelTest',
                'doc_host': 'https://Gippers.github.io',
                'git_url': 'https://github.com/Gippers/modelTest',
                'lib_path': 'modelTest'},
  'syms': { 'modelTest.core': { 'modelTest.core.get_links': ('core.html#get_links', 'modelTest/core.py'),
                                'modelTest.core.main': ('core.html#main', 'modelTest/core.py')}}}
