# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['stub', 'get_links', 'main']

# %% ../nbs/00_core.ipynb 3
import re
import sys
import urllib.request
import modal

# %% ../nbs/00_core.ipynb 4
stub = modal.Stub(name="link-scraper")


@stub.function()
def get_links(url):
    response = urllib.request.urlopen(url)
    html = response.read().decode("utf8")
    links = []
    for match in re.finditer('href="(.*?)"', html):
        links.append(match.group(1))
    return links


@stub.local_entrypoint()
def main(url):
    links = get_links.call(url)
    print(links)
